# Структура меток (аннотаций) EDF-файлов
Датасет мысленного произнесения слов — два языковых набора: **Russian** и **Spanish**.

In [134]:
import mne
import pandas as pd
from pathlib import Path

mne.set_log_level('WARNING')

BASE = Path(r'D:\Inner Speech Dataset\Inner Speech Dataset')

In [135]:
def annotations_summary(edf_path):
    raw = mne.io.read_raw_edf(edf_path, preload=False, verbose=False)
    ann = raw.annotations
    return pd.DataFrame({
        'onset':       ann.onset,
        'duration':    ann.duration,
        'description': ann.description,
    })


def show_label_structure(language):
    lang_dir = BASE / language
    edf_files = sorted(lang_dir.rglob('*.edf'))
    print(f'=== {language} ({len(edf_files)} subjects) ===')
    all_dfs = []
    for edf in edf_files:
        subject = edf.parent.name
        df = annotations_summary(edf)
        df.insert(0, 'subject', subject)
        df.insert(1, 'language', language)
        all_dfs.append(df)
        counts = df['description'].value_counts().to_dict()
        print(f'  {subject}: {len(df)} ann | labels: {sorted(df["description"].unique())}')
        print(f'    counts: {counts}')
    return pd.concat(all_dfs, ignore_index=True)

In [136]:
df_ru = show_label_structure('Russian')

=== Russian (12 subjects) ===
  sub1: 65 ann | labels: ['16:05:07', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'NEXT2': 6, 'LEFT1': 4, 'NEXT1': 4, 'BACK2': 4, 'BACK1': 4, 'FORWARD2': 4, 'FORWARD1': 4, 'LEFT2': 4, 'RIGHT2': 4, 'RIGHT1': 4, 'DOWN2': 4, 'DOWN1': 4, 'UP2': 4, 'UP1': 4, 'GZ': 3, 'GO': 3, '16:05:07': 1}
  sub10: 65 ann | labels: ['Annotations', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'RIGHT2': 4, 'LEFT1': 4, 'NEXT1': 4, 'BACK2': 4, 'BACK1': 4, 'FORWARD2': 4, 'FORWARD1': 4, 'LEFT2': 4, 'NEXT2': 4, 'GZ': 4, 'RIGHT1': 4, 'DOWN2': 4, 'DOWN1': 4, 'UP2': 4, 'UP1': 4, 'GO': 4, 'Annotations': 1}

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\271939701.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf_path, preload=False, verbose=False)

  sub11: 1367 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'GZ': 101, 'RIGHT2': 91, 'BACK2': 89, 'LEFT2': 89, 'DOWN2': 86, 'GO': 86, 'NEXT2': 86, 'DOWN1': 83, 'RIGHT1': 82, 'LEFT1': 82, 'UP2': 82, 'FORWARD1': 82, 'FORWARD2': 82, 'BACK1': 82, 'UP1': 82, 'NEXT1': 81, 'Annotation': 1}
  sub12: 478 ann | labels: ['10:54:20', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'UP1': 43, 'DOWN2': 36, 'BACK1': 35, 'DOWN1': 34, 'LEFT1': 32, 'FORWARD2': 31, 'LEFT2': 31, 'NEXT2': 30, 'FORWARD1': 30, 'BACK2': 30, 'NEXT1': 28, 'RIGHT2': 28, 'RIGHT1': 28, 'UP2': 26, 'GZ': 19, 'GO': 16, '10:54:20': 1}
  sub2: 1396 ann | labels: ['Annotations', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'NEXT1': 104, 'GO': 98, 'RIGHT1': 91, 'NEXT2': 89, 'GZ': 89, 'BACK2': 87, 'LEFT1': 86, 'RIGHT2': 86, 'DOWN2': 84, 'LEFT2': 84, 'BACK1': 84, 'DOWN1': 83, 'FORWARD1': 83, 'UP2': 83, 'FORWARD2': 82, 'UP1': 82, 'Annotations': 1}
  sub3: 65 ann | labels: ['12:56:00', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'RIGHT2': 4, 'LEFT1': 4, 'NEXT1': 4, 'BACK2': 4, 'BACK1': 4, 'FORWARD2': 4, 'FORWARD1': 4, 'LEFT2': 4, 'NEXT2': 4, 'GZ': 4, 'RIGHT1': 4, 'DOWN2': 4, 'DOWN1': 4, 'UP2': 4, 'UP1': 4, 'GO': 4, '12:56:00': 1}
  sub4: 1373 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'NEXT1': 132, 'UP1': 105, 'FORWARD2': 91, 'RIGHT1': 89, 'BACK1': 88, 'NEXT2': 87, 'FORWARD1': 87, 'UP2': 86, 'DOWN1': 86, 'LEFT1': 86, 'LEFT2': 85, 'RIGHT2': 84, 'DOWN2': 84, 'GO': 82, 'GZ': 71, 'BACK2': 29, 'Annotation': 1}
  sub5: 62 ann | labels: ['11:34:43', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'FORWARD2': 5, 'RIGHT2': 4, 'LEFT1': 4, 'NEXT1': 4, 'BACK2': 4, 'BACK1': 4, 'FORWARD1': 4, 'LEFT2': 4, 'NEXT2': 4, 'RIGHT1': 4, 'DOWN2': 4, 'DOWN1': 4, 'UP2': 4, 'UP1': 4, 'GZ': 2, 'GO': 2, '11:34:43': 1}
  sub6: 399 ann | labels: ['15:27:01', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'BACK1': 30, 'NEXT2': 29, 'NEXT1': 28, 'BACK2': 28, 'FORWARD2': 28, 'FORWARD1': 27, 'LEFT1': 26, 'DOWN1': 25, 'RIGHT2': 24, 'DOWN2': 24, 'UP1': 24, 'RIGHT1': 23, 'GO': 23, 'LEFT2': 22, 'UP2': 20, 'GZ': 17, '15:27:01': 1}
  sub7: 1344 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'NEXT1': 137, 'UP1': 108, 'BACK2': 95, 'FORWARD2': 93, 'UP2': 91, 'RIGHT1': 91, 'NEXT2': 88, 'BACK1': 88, 'FORWARD1': 87, 'LEFT1': 87, 'DOWN1': 86, 'RIGHT2': 85, 'LEFT2': 85, 'DOWN2': 85, 'GO': 21, 'GZ': 16, 'Annotation': 1}
  sub8: 1417 ann | labels: ['Annotations', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'LEFT2': 108, 'NEXT2': 100, 'DOWN2': 95, 'GZ': 90, 'GO': 89, 'UP2': 88, 'FORWARD2': 87, 'FORWARD1': 87, 'BACK2': 86, 'BACK1': 86, 'RIGHT2': 86, 'UP1': 85, 'RIGHT1': 83, 'DOWN1': 83, 'NEXT1': 82, 'LEFT1': 81, 'Annotations': 1}
  sub9: 1344 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'DOWN1': 124, 'DOWN2': 104, 'LEFT1': 95, 'UP2': 94, 'FORWARD2': 94, 'RIGHT1': 91, 'BACK1': 90, 'FORWARD1': 88, 'BACK2': 87, 'UP1': 86, 'NEXT1': 85, 'RIGHT2': 84, 'LEFT2': 84, 'NEXT2': 80, 'GO': 31, 'GZ': 26, 'Annotation': 1}

In [137]:
df_es = show_label_structure('Spanish')

=== Spanish (10 subjects) ===
  sub0: 1972 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'FORWARD2': 255, 'RIGHT2': 242, 'BACK2': 199, 'LEFT2': 186, 'DOWN2': 175, 'UP2': 164, 'FORWARD1': 159, 'LEFT1': 138, 'RIGHT1': 126, 'DOWN1': 119, 'BACK1': 110, 'UP1': 96, 'Annotation': 1, 'GO': 1, 'GZ': 1}
  sub1: 1574 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'BACK1': 168, 'FORWARD1': 154, 'FORWARD2': 151, 'RIGHT1': 133, 'RIGHT2': 131, 'DOWN1': 127, 'DOWN2': 126, 'BACK2': 125, 'LEFT1': 121, 'LEFT2': 116, 'UP2': 112, 'UP1': 107, 'Annotation': 1, 'GO': 1, 'GZ': 1}
  sub2: 2151 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'FORWARD1': 226, 'UP1': 214, 'LEFT2': 211, 'RIGHT2': 182, 'DOWN1': 181, 'FORWARD2': 175, 'BACK2': 169, 'RIGHT1': 168, 'BACK1': 165, 'UP2': 158, 'DOWN2': 151, 'LEFT1': 148, 'Annotation': 1, 'GO': 1, 'GZ': 1}
  sub3: 1044 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'LEFT1': 106, 'UP1': 94, 'DOWN1': 89, 'BACK2': 89, 'FORWARD1': 88, 'BACK1': 88, 'UP2': 86, 'RIGHT1': 86, 'FORWARD2': 86, 'DOWN2': 84, 'RIGHT2': 84, 'LEFT2': 61, 'Annotation': 1, 'GO': 1, 'GZ': 1}
  sub4: 1111 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'LEFT1': 110, 'BACK2': 100, 'UP1': 99, 'FORWARD1': 98, 'DOWN1': 95, 'FORWARD2': 95, 'LEFT2': 94, 'BACK1': 92, 'UP2': 91, 'RIGHT1': 89, 'DOWN2': 75, 'RIGHT2': 70, 'Annotation': 1, 'GO': 1, 'GZ': 1}
  sub5: 1600 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'FORWARD2': 185, 'RIGHT2': 176, 'DOWN2': 156, 'LEFT1': 143, 'FORWARD1': 142, 'UP2': 140, 'LEFT2': 128, 'RIGHT1': 122, 'DOWN1': 117, 'BACK2': 113, 'BACK1': 102, 'UP1': 73, 'Annotation': 1, 'GO': 1, 'GZ': 1}

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\271939701.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf_path, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\271939701.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf_path, preload=False, verbose=False)

  sub6: 1495 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'UP2': 160, 'FORWARD2': 136, 'FORWARD1': 132, 'UP1': 131, 'LEFT1': 131, 'DOWN2': 124, 'BACK2': 119, 'DOWN1': 115, 'LEFT2': 115, 'BACK1': 115, 'RIGHT2': 108, 'RIGHT1': 106, 'Annotation': 1, 'GO': 1, 'GZ': 1}
  sub7: 1563 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'FORWARD1': 154, 'DOWN2': 144, 'RIGHT1': 139, 'LEFT2': 139, 'LEFT1': 137, 'BACK1': 132, 'FORWARD2': 128, 'DOWN1': 123, 'RIGHT2': 119, 'UP1': 117, 'UP2': 115, 'BACK2': 113, 'Annotation': 1, 'GO': 1, 'GZ': 1}
  sub8: 1368 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'FORWARD2': 141, 'RIGHT2': 139, 'RIGHT1': 128, 'FORWARD1': 117, 'DOWN1': 112, 'DOWN2': 112, 'UP2': 109, 'BACK2': 108, 'LEFT1': 104, 'LEFT2': 104, 'UP1': 101, 'BACK1': 90, 'Annotation': 1, 'GO': 1, 'GZ': 1}

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\271939701.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf_path, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\271939701.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf_path, preload=False, verbose=False)

  sub9: 1210 ann | labels: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
    counts: {'BACK1': 127, 'LEFT1': 125, 'UP2': 105, 'UP1': 103, 'FORWARD2': 103, 'FORWARD1': 100, 'DOWN2': 99, 'RIGHT1': 99, 'RIGHT2': 97, 'LEFT2': 90, 'DOWN1': 80, 'BACK2': 79, 'Annotation': 1, 'GO': 1, 'GZ': 1}

## Сводная таблица: количество аннотаций по меткам

## Выявление участников с нетипичной методологией (Russian)

In [138]:
import numpy as np

def analyze_methodology(language='Russian'):
    lang_dir = BASE / language
    edf_files = sorted(lang_dir.rglob('*.edf'))

    rows = []
    for edf in edf_files:
        subject = edf.parent.name
        raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
        ann = raw.annotations

        onsets = ann.onset
        n_ann = len(onsets)

        if n_ann < 2:
            rows.append({'subject': subject, 'n_annotations': n_ann,
                         'median_gap_s': None, 'max_gap_s': None, 'flag': 'too few'})
            continue

        gaps = np.diff(onsets)  # интервалы между соседними аннотациями
        rows.append({
            'subject':       subject,
            'n_annotations': n_ann,
            'median_gap_s':  round(float(np.median(gaps)), 2),
            'max_gap_s':     round(float(np.max(gaps)), 2),
        })

    df = pd.DataFrame(rows).sort_values('subject')

    # Типичная методология: 1 метка = 1 произнесение → много меток, короткие равномерные интервалы
    # Нетипичная: 1 метка = N произнесений → мало меток, большие/неравномерные интервалы
    median_n = df['n_annotations'].median()
    df['flag'] = df['n_annotations'].apply(
        lambda x: '⚠ нетипичный' if x < median_n * 0.5 else 'норма'
    )

    return df

df_method = analyze_methodology('Russian')
display(df_method)

print('\nПодозрительные участники:')
display(df_method[df_method['flag'] != 'норма'])

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2673242694.py:10: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)

   subject  n_annotations  median_gap_s  max_gap_s          flag
0     sub1             65         48.90     154.17  ⚠ нетипичный
1    sub10             65         40.22      89.60  ⚠ нетипичный
2    sub11           1367          3.20     263.88         норма
3    sub12            478          4.46     186.40         норма
4     sub2           1396          2.14     199.84         норма
5     sub3             65         32.86     236.93  ⚠ нетипичный
6     sub4           1373          2.35     178.11         норма
7     sub5             62         46.74     183.51  ⚠ нетипичный
8     sub6            399          4.66     173.64  ⚠ нетипичный
9     sub7           1344          2.39     175.32         норма
10    sub8           1417          1.98     293.72         норма
11    sub9           1344          1.82     157.78         норма

Подозрительные участники:

  subject  n_annotations  median_gap_s  max_gap_s          flag
0    sub1             65         48.90     154.17  ⚠ нетипичный
1   sub10             65         40.22      89.60  ⚠ нетипичный
5    sub3             65         32.86     236.93  ⚠ нетипичный
7    sub5             62         46.74     183.51  ⚠ нетипичный
8    sub6            399          4.66     173.64  ⚠ нетипичный

In [139]:
df_all = pd.concat([df_ru, df_es], ignore_index=True)

pivot = (
    df_all
    .groupby(['language', 'subject', 'description'])
    .size()
    .reset_index(name='count')
    .pivot_table(index=['language', 'subject'], columns='description', values='count', fill_value=0)
)
display(pivot)

description       10:54:20  11:34:43  12:56:00  15:27:01  16:05:07  \
language subject
Russian  sub1            0         0         0         0         1
         sub10           0         0         0         0         0
         sub11           0         0         0         0         0
         sub12           1         0         0         0         0
         sub2            0         0         0         0         0
         sub3            0         0         1         0         0
         sub4            0         0         0         0         0
         sub5            0         1         0         0         0
         sub6            0         0         0         1         0
         sub7            0         0         0         0         0
         sub8            0         0         0         0         0
         sub9            0         0         0         0         0
Spanish  sub0            0         0         0         0         0
         sub1            0         0         0         0         0
         sub2            0         0         0         0         0
         sub3            0         0         0         0         0
         sub4            0         0         0         0         0
         sub5            0         0         0         0         0
         sub6            0         0         0         0         0
         sub7            0         0         0         0         0
         sub8            0         0         0         0         0
         sub9            0         0         0         0         0

description       Annotation  Annotations  BACK1  BACK2  DOWN1  ...  GO   GZ  \
language subject                                                ...
Russian  sub1              0            0      4      4      4  ...   3    3
         sub10             0            1      4      4      4  ...   4    4
         sub11             1            0     82     89     83  ...  86  101
         sub12             0            0     35     30     34  ...  16   19
         sub2              0            1     84     87     83  ...  98   89
         sub3              0            0      4      4      4  ...   4    4
         sub4              1            0     88     29     86  ...  82   71
         sub5              0            0      4      4      4  ...   2    2
         sub6              0            0     30     28     25  ...  23   17
         sub7              1            0     88     95     86  ...  21   16
         sub8              0            1     86     86     83  ...  89   90
         sub9              1            0     90     87    124  ...  31   26
Spanish  sub0              1            0    110    199    119  ...   1    1
         sub1              1            0    168    125    127  ...   1    1
         sub2              1            0    165    169    181  ...   1    1
         sub3              1            0     88     89     89  ...   1    1
         sub4              1            0     92    100     95  ...   1    1
         sub5              1            0    102    113    117  ...   1    1
         sub6              1            0    115    119    115  ...   1    1
         sub7              1            0    132    113    123  ...   1    1
         sub8              1            0     90    108    112  ...   1    1
         sub9              1            0    127     79     80  ...   1    1

description       LEFT1  LEFT2  NEXT1  NEXT2  RIGHT1  RIGHT2  UP1  UP2
language subject
Russian  sub1         4      4      4      6       4       4    4    4
         sub10        4      4      4      4       4       4    4    4
         sub11       82     89     81     86      82      91   82   82
         sub12       32     31     28     30      28      28   43   26
         sub2        86     84    104     89      91      86   82   83
         sub3         4      4      4      4       4       4    4    4
         sub4        86     85    132     87      89      84  105   86
         sub5         4      4      4      4       4       4    4    4
         sub6        26     22     28     29      23      24   24   20
         sub7        87     85    137     88      91      85  108   91
         sub8        81    108     82    100      83      86   85   88
         sub9        95     84     85     80      91      84   86   94
Spanish  sub0       138    186      0      0     126     242   96  164
         sub1       121    116      0      0     133     131  107  112
         sub2       148    211      0      0     168     182  214  158
         sub3       106     61      0      0      86      84   94   86
         sub4       110     94      0      0      89      70   99   91
         sub5       143    128      0      0     122     176   73  140
         sub6       131    115      0      0     106     108  131  160
         sub7       137    139      0      0     139     119  117  115
         sub8       104    104      0      0     128     139  101  109
         sub9       125     90      0      0      99      97  103  105

[22 rows x 23 columns]

In [140]:
print('Все уникальные метки по языкам:')
for lang, grp in df_all.groupby('language'):
    print(f'  {lang}: {sorted(grp["description"].unique())}')

Все уникальные метки по языкам:
  Russian: ['10:54:20', '11:34:43', '12:56:00', '15:27:01', '16:05:07', 'Annotation', 'Annotations', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']
  Spanish: ['Annotation', 'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2', 'GO', 'GZ', 'LEFT1', 'LEFT2', 'RIGHT1', 'RIGHT2', 'UP1', 'UP2']

---\n## Информация по эпохам (.fif файлы)

In [141]:
def epochs_info(language):
    lang_dir = BASE / language
    fif_files = sorted(lang_dir.rglob('*-epo.fif'))

    rows = []
    for fif in fif_files:
        subject = fif.parent.name
        epochs = mne.read_epochs(fif, preload=False, verbose=False)

        n_trials   = len(epochs)
        n_channels = len(epochs.ch_names)
        sfreq      = epochs.info['sfreq']
        tmin       = round(epochs.tmin, 4)
        tmax       = round(epochs.tmax, 4)
        epoch_len  = round(tmax - tmin, 4)
        n_times    = epochs.times.shape[0]

        event_counts = {k: v for k, v in zip(
            epochs.event_id.keys(),
            [(epochs.events[:, 2] == v).sum() for v in epochs.event_id.values()]
        )}

        rows.append({
            'language':    language,
            'subject':     subject,
            'n_trials':    n_trials,
            'n_channels':  n_channels,
            'sfreq_Hz':    sfreq,
            'tmin_s':      tmin,
            'tmax_s':      tmax,
            'epoch_len_s': epoch_len,
            'n_timepoints':n_times,
            'event_id':    epochs.event_id,
            'trial_counts':event_counts,
        })

    return pd.DataFrame(rows)


df_epo_ru = epochs_info('Russian')
df_epo_es = epochs_info('Spanish')
df_epo_all = pd.concat([df_epo_ru, df_epo_es], ignore_index=True)

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2312130166.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2312130166.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2312130166.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2312130166.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2312130166.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2312130166.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2312130166.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2312130166.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)

In [142]:
display(df_epo_all[['language','subject','n_trials','n_channels','sfreq_Hz','tmin_s','tmax_s','epoch_len_s','n_timepoints']])

,language,subject,n_trials,n_channels,sfreq_Hz,tmin_s,tmax_s,epoch_len_s,n_timepoints
0,Russian,sub1,116,37,500.0,-1.0,-0.002,0.998,500
1,Russian,sub10,115,37,500.0,-1.0,-0.002,0.998,500
2,Russian,sub11,1238,38,500.0,-1.0,-0.002,0.998,500
3,Russian,sub12,543,37,500.0,-1.0,-0.002,0.998,500
4,Russian,sub2,1267,37,500.0,-1.0,-0.002,0.998,500
5,Russian,sub3,115,37,500.0,-1.0,-0.002,0.998,500
6,Russian,sub4,1278,37,500.0,-1.0,-0.002,0.998,500
7,Russian,sub5,116,37,500.0,-1.0,-0.002,0.998,500
8,Russian,sub6,464,37,500.0,-1.0,-0.002,0.998,500
9,Russian,sub7,1365,37,500.0,-1.0,-0.002,0.998,500
10,Russian,sub8,1296,37,500.0,-1.0,-0.002,0.998,500
11,Russian,sub9,1360,35,250.0,-1.0,0.000,1.000,251
12,Spanish,sub0,2028,38,500.0,-1.0,-0.002,0.998,500
13,Spanish,sub1,1630,38,500.0,-1.0,-0.002,0.998,500
14,Spanish,sub2,2207,38,500.0,-1.0,-0.002,0.998,500
15,Spanish,sub3,1100,38,500.0,-1.0,-0.002,0.998,500
16,Spanish,sub4,1167,38,500.0,-1.0,-0.002,0.998,500
17,Spanish,sub5,1656,38,500.0,-1.0,-0.002,0.998,500
18,Spanish,sub6,1551,38,500.0,-1.0,-0.002,0.998,500
19,Spanish,sub7,1619,38,500.0,-1.0,-0.002,0.998,500
20,Spanish,sub8,1424,38,500.0,-1.0,-0.002,0.998,500
21,Spanish,sub9,1266,38,500.0,-1.0,-0.002,0.998,500

In [143]:
# Количество трайлов по словам — сводная таблица
trial_df = pd.DataFrame(df_epo_all['trial_counts'].tolist())
trial_df.insert(0, 'subject', df_epo_all['subject'].values)
trial_df.insert(0, 'language', df_epo_all['language'].values)
trial_df = trial_df.set_index(['language', 'subject'])
display(trial_df)

                  BACK1  BACK2  DOWN1  DOWN2  FORWARD1  FORWARD2   GO  LEFT1  \
language subject
Russian  sub1         4      4      4      4         4         4   59      4
         sub10        4      4      4      4         4         4   59      4
         sub11       82     89     83     86        82        82   59     82
         sub12       35     30     34     36        30        31  101     32
         sub2        84     87     83     84        83        82   59     86
         sub3         4      4      4      4         4         4   59      4
         sub4        88     29     86     84        87        91   59     86
         sub5         4      4      4      4         4         5   59      4
         sub6        30     28     25     24        27        28  106     26
         sub7        88     95     86     85        87        93   59     87
         sub8        86     86     83     95        87        87   59     81
         sub9        90     87    124    104        88        94   74     95
Spanish  sub0       110    199    119    175       159       255   59    138
         sub1       168    125    127    126       154       151   59    121
         sub2       165    169    181    151       226       175   59    148
         sub3        88     89     89     84        88        86   59    106
         sub4        92    100     95     75        98        95   59    110
         sub5       102    113    117    156       142       185   59    143
         sub6       115    119    115    124       132       136   59    131
         sub7       132    113    123    144       154       128   59    137
         sub8        90    108    112    112       117       141   59    104
         sub9       127     79     80     99       100       103   59    125

                  LEFT2  NEXT1  NEXT2  RIGHT1  RIGHT2  UP1  UP2
language subject
Russian  sub1         4    4.0    5.0       4       4    4    4
         sub10        4    4.0    4.0       4       4    4    4
         sub11       89   81.0   86.0      82      91   82   82
         sub12       31   28.0   30.0      28      28   43   26
         sub2        84  104.0   89.0      91      86   82   83
         sub3         4    4.0    4.0       4       4    4    4
         sub4        85  132.0   87.0      89      84  105   86
         sub5         4    4.0    4.0       4       4    4    4
         sub6        22   28.0   29.0      23      24   24   20
         sub7        85  137.0   88.0      91      85  108   91
         sub8       108   82.0  100.0      83      86   85   88
         sub9        84   85.0   80.0      91      84   86   94
Spanish  sub0       186    NaN    NaN     126     242   96  164
         sub1       116    NaN    NaN     133     131  107  112
         sub2       211    NaN    NaN     168     182  214  158
         sub3        61    NaN    NaN      86      84   94   86
         sub4        94    NaN    NaN      89      70   99   91
         sub5       128    NaN    NaN     122     176   73  140
         sub6       115    NaN    NaN     106     108  131  160
         sub7       139    NaN    NaN     139     119  117  115
         sub8       104    NaN    NaN     128     139  101  109
         sub9        90    NaN    NaN      99      97  103  105

## Идентификация EMG каналов

In [144]:
EMG_CHANNELS = {'B1+', 'B1-', 'B2+', 'B2-', 'EMG1', 'EMG2', 'Pharing1', 'Pharing2'}

def show_channel_names(language):
    lang_dir = BASE / language
    edf_files = sorted(lang_dir.rglob('*.edf'))

    rows = []
    for edf in edf_files:
        subject = edf.parent.name
        raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
        ch_names = raw.ch_names
        emg_present = [ch for ch in ch_names if ch in EMG_CHANNELS]
        eeg_channels = [ch for ch in ch_names if ch not in EMG_CHANNELS]
        rows.append({
            'language':    language,
            'subject':     subject,
            'n_total':     len(ch_names),
            'n_eeg':       len(eeg_channels),
            'n_emg':       len(emg_present),
            'emg_channels': emg_present if emg_present else None,
        })

    return pd.DataFrame(rows)


df_ch_ru = show_channel_names('Russian')
df_ch_es = show_channel_names('Spanish')
df_ch_all = pd.concat([df_ch_ru, df_ch_es], ignore_index=True)

display(df_ch_all.set_index(['language', 'subject']))

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\4114931880.py:10: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\4114931880.py:10: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\4114931880.py:10: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\4114931880.py:10: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\4114931880.py:10: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)

                  n_total  n_eeg  n_emg                      emg_channels
language subject
Russian  sub1          37     37      0                              None
         sub10         37     37      0                              None
         sub11         44     40      4              [B1+, B1-, B2+, B2-]
         sub12         37     37      0                              None
         sub2          37     37      0                              None
         sub3          37     37      0                              None
         sub4          37     37      0                              None
         sub5          37     37      0                              None
         sub6          37     37      0                              None
         sub7          37     37      0                              None
         sub8          39     37      2                        [B1+, B1-]
         sub9          35     35      0                              None
Spanish  sub0          38     38      0                              None
         sub1          38     38      0                              None
         sub2          38     38      0                              None
         sub3          38     38      0                              None
         sub4          38     38      0                              None
         sub5          38     38      0                              None
         sub6          44     40      4  [EMG1, EMG2, Pharing1, Pharing2]
         sub7          44     40      4  [EMG1, EMG2, Pharing1, Pharing2]
         sub8          44     40      4  [EMG1, EMG2, Pharing1, Pharing2]
         sub9          44     40      4  [EMG1, EMG2, Pharing1, Pharing2]

In [145]:
def check_emg_in_fif(language):
    lang_dir = BASE / language
    fif_files = sorted(lang_dir.rglob('*-epo.fif'))

    rows = []
    for fif in fif_files:
        subject = fif.parent.name
        epochs = mne.read_epochs(fif, preload=False, verbose=False)

        ch_types = {ch: mne.channel_type(epochs.info, i)
                    for i, ch in enumerate(epochs.ch_names)}

        emg_info = {ch: ch_types[ch] for ch in epochs.ch_names if ch in EMG_CHANNELS}

        rows.append({
            'language':    language,
            'subject':     subject,
            'n_total':     len(epochs.ch_names),
            'emg_found':   emg_info if emg_info else None,
        })

    return pd.DataFrame(rows)


fif_emg_ru = check_emg_in_fif('Russian')
fif_emg_es = check_emg_in_fif('Spanish')
fif_emg_all = pd.concat([fif_emg_ru, fif_emg_es], ignore_index=True)

print('EMG каналы в fif (имя → тип):')
display(fif_emg_all.set_index(['language', 'subject']))

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1464857694.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1464857694.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1464857694.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1464857694.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1464857694.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1464857694.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1464857694.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1464857694.py:8: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)

EMG каналы в fif (имя → тип):

                  n_total emg_found
language subject
Russian  sub1          37      None
         sub10         37      None
         sub11         38      None
         sub12         37      None
         sub2          37      None
         sub3          37      None
         sub4          37      None
         sub5          37      None
         sub6          37      None
         sub7          37      None
         sub8          37      None
         sub9          35      None
Spanish  sub0          38      None
         sub1          38      None
         sub2          38      None
         sub3          38      None
         sub4          38      None
         sub5          38      None
         sub6          38      None
         sub7          38      None
         sub8          38      None
         sub9          38      None

In [146]:
def show_fif_channels(language):
    lang_dir = BASE / language
    fif_files = sorted(lang_dir.rglob('*-epo.fif'))

    for fif in fif_files:
        subject = fif.parent.name
        epochs = mne.read_epochs(fif, preload=False, verbose=False)
        print(f"[{language}] {subject} ({len(epochs.ch_names)} каналов):")
        print(f"  {epochs.ch_names}")
        print()

show_fif_channels('Russian')
show_fif_channels('Spanish')

[Russian] sub1 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCz', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'T7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P5', 'P3', 'Pz', 'P4', 'P6', 'T6', 'PO7', 'PO3', 'POz', 'PO4', 'PO8', 'O1', 'Oz', 'O2']

[Russian] sub10 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'FCz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'Oz', 'PO8']

[Russian] sub11 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'Fcz', 'F4', 'F8', 'Ft7', 'Fc3', 'Fc4', 'Ft8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'Tp7', 'Cp3', 'Cpz', 'Cp4', 'Tp8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'Po3', 'Poz', 'Po4', 'P6', 'Po7', 'O1', 'O2', 'Oz', 'Po8']

[Russian] sub12 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCz', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'T7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P5', 'P3', 'Pz', 'P4', 'P6', 'T6', 'PO7', 'PO3', 'POz', 'PO4', 'PO8', 'O1', 'Oz', 'O2']

[Russian] sub2 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'FCz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'Oz', 'PO8']

[Russian] sub3 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCz', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'T7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P5', 'P3', 'Pz', 'P4', 'P6', 'T6', 'PO7', 'PO3', 'POz', 'PO4', 'PO8', 'O1', 'Oz', 'O2']

[Russian] sub4 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCz', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'Oz', 'O2', 'PO8']

[Russian] sub5 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCz', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'T7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P5', 'P3', 'Pz', 'P4', 'P6', 'T6', 'PO7', 'PO3', 'POz', 'PO4', 'PO8', 'O1', 'Oz', 'O2']

[Russian] sub6 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCz', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'T7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P5', 'P3', 'Pz', 'P4', 'P6', 'T6', 'PO7', 'PO3', 'POz', 'PO4', 'PO8', 'O1', 'Oz', 'O2']

[Russian] sub7 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FCz', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'Oz', 'O2', 'PO8']

[Russian] sub8 (37 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'FCz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'Oz', 'PO8']

[Russian] sub9 (35 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'PO8']

[Spanish] sub0 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'FCz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'Oz', 'PO8']

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2858065670.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2858065670.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2858065670.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2858065670.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2858065670.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2858065670.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2858065670.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2858065670.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)

[Spanish] sub1 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'FCz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'Oz', 'PO8']

[Spanish] sub2 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'FCz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'Oz', 'PO8']

[Spanish] sub3 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'FCz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'Oz', 'PO8']

[Spanish] sub4 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'FCz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'Oz', 'PO8']

[Spanish] sub5 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'FCz', 'F4', 'F8', 'FT7', 'FC3', 'FC4', 'FT8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'TP7', 'CP3', 'CPz', 'CP4', 'TP8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'PO3', 'POz', 'PO4', 'P6', 'PO7', 'O1', 'O2', 'Oz', 'PO8']

[Spanish] sub6 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'Fcz', 'F4', 'F8', 'Ft7', 'Fc3', 'Fc4', 'Ft8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'Tp7', 'Cp3', 'Cpz', 'Cp4', 'Tp8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'Po3', 'Poz', 'Po4', 'P6', 'Po7', 'O1', 'O2', 'Oz', 'Po8']

[Spanish] sub7 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'Fcz', 'F4', 'F8', 'Ft7', 'Fc3', 'Fc4', 'Ft8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'Tp7', 'Cp3', 'Cpz', 'Cp4', 'Tp8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'Po3', 'Poz', 'Po4', 'P6', 'Po7', 'O1', 'O2', 'Oz', 'Po8']

[Spanish] sub8 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'Fcz', 'F4', 'F8', 'Ft7', 'Fc3', 'Fc4', 'Ft8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'Tp7', 'Cp3', 'Cpz', 'Cp4', 'Tp8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'Po3', 'Poz', 'Po4', 'P6', 'Po7', 'O1', 'O2', 'Oz', 'Po8']

[Spanish] sub9 (38 каналов):
  ['Fp1', 'Fpz', 'Fp2', 'F7', 'F3', 'Fz', 'Fcz', 'F4', 'F8', 'Ft7', 'Fc3', 'Fc4', 'Ft8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'Tp7', 'Cp3', 'Cpz', 'Cp4', 'Tp8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'P5', 'Po3', 'Poz', 'Po4', 'P6', 'Po7', 'O1', 'O2', 'Oz', 'Po8']

## Препроцессинг в fif-файлах

In [147]:
def show_preprocessing(language):
    lang_dir = BASE / language
    fif_files = sorted(lang_dir.rglob('*-epo.fif'))

    for fif in fif_files:
        subject = fif.parent.name
        epochs = mne.read_epochs(fif, preload=False, verbose=False)
        info = epochs.info

        print(f"[{language}] {subject}")
        print(f"  Фильтры : highpass={info['highpass']} Hz, lowpass={info['lowpass']} Hz")
        print(f"  Baseline: {epochs.baseline}")
        print(f"  Reject  : {epochs.reject}")
        print(f"  Flat    : {epochs.flat}")

        # SSP проекторы
        projs = info.get('projs', [])
        if projs:
            print(f"  Проекторы (SSP): {[p['desc'] for p in projs]}")
        else:
            print(f"  Проекторы (SSP): нет")

        # История обработки
        proc = info.get('proc_history', [])
        if proc:
            for step in proc:
                creator = step.get('creator', '?')
                date    = step.get('date', '?')
                print(f"  proc_history: {creator} @ {date}")
                maxinfo = step.get('max_info', {})
                if maxinfo:
                    print(f"    max_info: {maxinfo}")
        else:
            print(f"  proc_history: нет")

        print()

show_preprocessing('Russian')
show_preprocessing('Spanish')

[Russian] sub1
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub10
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub11
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub12
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub2
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub3
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub4
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub5
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub6
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub7
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub8
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Russian] sub9
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Spanish] sub0
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Spanish] sub1
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2378826824.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2378826824.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2378826824.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2378826824.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2378826824.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2378826824.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2378826824.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2378826824.py:7: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)

[Spanish] sub2
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Spanish] sub3
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Spanish] sub4
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Spanish] sub5
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Spanish] sub6
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Spanish] sub7
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Spanish] sub8
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

[Spanish] sub9
  Фильтры : highpass=1.0 Hz, lowpass=70.0 Hz
  Baseline: (0.0, 0.0)
  Reject  : None
  Flat    : None
  Проекторы (SSP): нет
  proc_history: нет

In [148]:
# Ищем ICA-файлы рядом с данными
print('=== Поиск *-ica.fif файлов ===')
for language in ('Russian', 'Spanish'):
    ica_files = sorted((BASE / language).rglob('*ica*'))
    if ica_files:
        for f in ica_files:
            print(f'  {f}')
    else:
        print(f'  [{language}] ICA-файлов не найдено')

print()

# Смотрим description и комментарии внутри fif
print('=== info[description] и info[experimenter] в fif ===')
for language in ('Russian', 'Spanish'):
    for fif in sorted((BASE / language).rglob('*-epo.fif')):
        subject = fif.parent.name
        epochs = mne.read_epochs(fif, preload=False, verbose=False)
        info = epochs.info
        desc  = info.get('description', None)
        exp   = info.get('experimenter', None)
        notes = [f'description={desc!r}' if desc else None,
                 f'experimenter={exp!r}' if exp else None]
        notes = [n for n in notes if n]
        print(f'  [{language}] {subject}: {", ".join(notes) if notes else "нет мета-комментариев"}')

=== Поиск *-ica.fif файлов ===
  [Russian] ICA-файлов не найдено
  [Spanish] ICA-файлов не найдено

=== info[description] и info[experimenter] в fif ===
  [Russian] sub1: нет мета-комментариев
  [Russian] sub10: нет мета-комментариев
  [Russian] sub11: нет мета-комментариев
  [Russian] sub12: нет мета-комментариев
  [Russian] sub2: нет мета-комментариев
  [Russian] sub3: нет мета-комментариев
  [Russian] sub4: нет мета-комментариев
  [Russian] sub5: нет мета-комментариев
  [Russian] sub6: нет мета-комментариев
  [Russian] sub7: нет мета-комментариев
  [Russian] sub8: нет мета-комментариев
  [Russian] sub9: нет мета-комментариев
  [Spanish] sub0: нет мета-комментариев
  [Spanish] sub1: нет мета-комментариев
  [Spanish] sub2: нет мета-комментариев

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2870914225.py:18: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2870914225.py:18: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2870914225.py:18: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2870914225.py:18: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2870914225.py:18: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2870914225.py:18: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2870914225.py:18: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2870914225.py:18: RuntimeWarning: The events passed to the Epochs constructor are not chronologically ordered.
  epochs = mne.read_epochs(fif, preload=False, verbose=False)

  [Spanish] sub3: нет мета-комментариев
  [Spanish] sub4: нет мета-комментариев
  [Spanish] sub5: нет мета-комментариев
  [Spanish] sub6: нет мета-комментариев
  [Spanish] sub7: нет мета-комментариев
  [Spanish] sub8: нет мета-комментариев
  [Spanish] sub9: нет мета-комментариев

## Препроцессинг в EDF-файлах

In [149]:
def show_edf_preprocessing(language):
    lang_dir = BASE / language
    edf_files = sorted(lang_dir.rglob('*.edf'))

    for edf in edf_files:
        subject = edf.parent.name
        raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
        info = raw.info

        print(f"[{language}] {subject}")
        print(f"  Фильтры     : highpass={info['highpass']} Hz, lowpass={info['lowpass']} Hz")
        print(f"  Доп. инфо   : description={info.get('description', None)!r}")
        print(f"  experimenter: {info.get('experimenter', None)!r}")

        # EDF-заголовок доступен через _raw_extras
        extras = getattr(raw, '_raw_extras', [{}])
        if extras:
            ex = extras[0]
            print(f"  EDF subtype      : {ex.get('subtype', '?')}")
            print(f"  EDF subject_info : {ex.get('subject_info', '?')}")
            print(f"  EDF recording    : {ex.get('rec_id', '?')}")
            prefilter = ex.get('prefilter', None)
            if not prefilter:
                # попробуем достать из сигналов
                prefilter = [s.get('prefilter', '') for s in ex.get('signals', [])]
                prefilter = list(dict.fromkeys(filter(None, prefilter)))  # уникальные
            print(f"  Prefilter field  : {prefilter}")

        proc = info.get('proc_history', [])
        if proc:
            for step in proc:
                print(f"  proc_history: {step.get('creator','?')} @ {step.get('date','?')}")
        else:
            print(f"  proc_history: нет")

        print()

show_edf_preprocessing('Russian')
show_edf_preprocessing('Spanish')

[Russian] sub1
  Фильтры     : highpass=0.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub10
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub11
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1726170161.py:7: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)

[Russian] sub12
  Фильтры     : highpass=0.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub2
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub3
  Фильтры     : highpass=0.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub4
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub5
  Фильтры     : highpass=0.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub6
  Фильтры     : highpass=0.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub7
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub8
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Russian] sub9
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Spanish] sub0
  Фильтры     : highpass=1.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Spanish] sub1
  Фильтры     : highpass=1.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Spanish] sub2
  Фильтры     : highpass=1.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Spanish] sub3
  Фильтры     : highpass=1.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Spanish] sub4
  Фильтры     : highpass=1.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Spanish] sub5
  Фильтры     : highpass=1.0 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Spanish] sub6
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1726170161.py:7: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1726170161.py:7: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)

[Spanish] sub7
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Spanish] sub8
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

[Spanish] sub9
  Фильтры     : highpass=0.5 Hz, lowpass=70.0 Hz
  Доп. инфо   : description=None
  experimenter: None
  EDF subtype      : edf
  EDF subject_info : ?
  EDF recording    : ?
  Prefilter field  : []
  proc_history: нет

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1726170161.py:7: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1726170161.py:7: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)

In [151]:
import mne
import pandas as pd
from pathlib import Path

mne.set_log_level('WARNING')

BASE = Path(r'D:\Inner Speech Dataset\Inner Speech Dataset')

INFORMATIVE_LABELS = {
    'BACK1', 'BACK2', 'DOWN1', 'DOWN2', 'FORWARD1', 'FORWARD2',
    'GO', 'GZ', 'LEFT1', 'LEFT2', 'NEXT1', 'NEXT2',
    'RIGHT1', 'RIGHT2', 'UP1', 'UP2'
}

rows = []
for language in ('Russian', 'Spanish'):
    for edf in sorted((BASE / language).rglob('*edited.edf')):
        subject = edf.parent.name
        raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
        labels = set(raw.annotations.description)
        garbage = labels - INFORMATIVE_LABELS
        if garbage:
            rows.append({
                'language': language,
                'subject':  subject,
                'file':     edf.name,
                'garbage_labels': sorted(garbage),
                'all_labels':     sorted(labels),
            })

if rows:
    df_garbage = pd.DataFrame(rows)
    print(f'Файлов с мусорными метками: {len(df_garbage)}\n')
    for _, r in df_garbage.iterrows():
        print(f"[{r['language']}] {r['subject']} / {r['file']}")
        print(f"  мусор : {r['garbage_labels']}")
        print(f"  все   : {r['all_labels']}")
        print()
    display(df_garbage[['language', 'subject', 'file', 'garbage_labels']])
else:
    print('Мусорных меток не найдено — все файлы содержат только информативные метки.')

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2855082622.py:19: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2855082622.py:19: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2855082622.py:19: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2855082622.py:19: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\2855082622.py:19: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)

Мусорных меток не найдено — все файлы содержат только информативные метки.

In [152]:
import mne
import pandas as pd
from pathlib import Path

mne.set_log_level('WARNING')

BASE = Path(r'D:\Inner Speech Dataset\Inner Speech Dataset')

def epochs_per_trial(language):
    rows = []
    for fif in sorted((BASE / language).rglob('*-clean-epo.fif')):
        subject = fif.parent.name
        epochs = mne.read_epochs(fif, preload=False, verbose=False)

        # обратный маппинг: event_id → label
        id2label = {v: k for k, v in epochs.event_id.items()}

        for i, (onset_sample, _, event_code) in enumerate(epochs.events):
            onset_sec = onset_sample / epochs.info['sfreq']
            rows.append({
                'language':   language,
                'subject':    subject,
                'trial_idx':  i,
                'label':      id2label.get(event_code, f'unknown_{event_code}'),
                'event_code': event_code,
                'onset_s':    round(onset_sec, 4),
                'tmin_s':     round(epochs.tmin, 4),
                'tmax_s':     round(epochs.tmax, 4),
                'sfreq_Hz':   epochs.info['sfreq'],
                'n_channels': len(epochs.ch_names),
            })
    return pd.DataFrame(rows)

df_ru = epochs_per_trial('Russian')
df_es = epochs_per_trial('Spanish')
df_all = pd.concat([df_ru, df_es], ignore_index=True)

print(f'Всего эпох: {len(df_all)}')
print(f"  Russian : {len(df_ru)}")
print(f"  Spanish : {len(df_es)}")
print()

# Сводка по испытуемым и меткам
pivot = (
    df_all
    .groupby(['language', 'subject', 'label'])
    .size()
    .reset_index(name='n_epochs')
    .pivot_table(index=['language', 'subject'], columns='label', values='n_epochs', fill_value=0)
)
print('=== Количество эпох по меткам (clean) ===')
display(pivot)

print('\n=== Полная таблица по каждой эпохе ===')
display(df_all)

Всего эпох: 28259
  Russian : 12601
  Spanish : 15658

=== Количество эпох по меткам (clean) ===

label             BACK1  BACK2  DOWN1  DOWN2  FORWARD1  FORWARD2   GO   GZ  \
language subject
Russian  sub1        48     48     48     48        48        48   90   90
         sub10       48     48     48     48        48        48  120  120
         sub11       82     89     83     86        82        82   86  100
         sub12       35     30     34     36        30        31   16   19
         sub2        84     87     83     84        83        82   98   89
         sub3        48     48     48     48        48        48  120  120
         sub4        88     29     86     84        87        91   82   71
         sub5        48     48     48     48        48        60   60   60
         sub6        30     28     25     24        27        28   23   17
         sub7        88     95     86     85        87        93   21   16
         sub8        86     86     83     95        87        87   89   90
         sub9        90     87    124    104        88        94   31   26
Spanish  sub0       110    199    119    175       159       255   30   30
         sub1       168    125    127    126       154       151   30   30
         sub2       165    169    181    151       226       175   30   30
         sub3        88     89     89     84        88        86   30   30
         sub4        92    100     95     75        98        95   30   30
         sub5       102    113    117    156       142       185   30   30
         sub6       115    119    115    124       132       136   30   30
         sub7       132    113    123    144       154       128   30   30
         sub8        90    108    112    112       117       141   30   30
         sub9       127     79     80     99       100       103   30   30

label             LEFT1  LEFT2  NEXT1  NEXT2  RIGHT1  RIGHT2  UP1  UP2
language subject
Russian  sub1        48     48     48     60      48      48   48   48
         sub10       48     48     48     48      48      48   48   48
         sub11       82     89     81     86      82      91   82   82
         sub12       32     31     28     30      28      28   43   26
         sub2        86     84    104     89      91      86   82   83
         sub3        48     48     48     48      48      48   48   48
         sub4        86     85    132     87      89      84  105   86
         sub5        48     48     48     48      48      48   48   48
         sub6        26     22     28     29      23      24   24   20
         sub7        87     85    137     88      91      85  108   91
         sub8        81    108     82    100      83      86   85   88
         sub9        95     84     85     80      91      84   86   94
Spanish  sub0       138    186      0      0     126     242   96  164
         sub1       121    116      0      0     133     131  107  112
         sub2       148    211      0      0     168     182  214  158
         sub3       106     61      0      0      86      84   94   86
         sub4       110     94      0      0      89      70   99   91
         sub5       143    128      0      0     122     176   73  140
         sub6       131    115      0      0     106     108  131  160
         sub7       137    139      0      0     139     119  117  115
         sub8       104    104      0      0     128     139  101  109
         sub9       125     90      0      0      99      97  103  105

=== Полная таблица по каждой эпохе ===

,language,subject,trial_idx,label,event_code,onset_s,tmin_s,tmax_s,sfreq_Hz,n_channels
0,Russian,sub1,0,GZ,8,9.440,0.0,0.998,500.0,37
1,Russian,sub1,1,GZ,8,10.440,0.0,0.998,500.0,37
2,Russian,sub1,2,GZ,8,11.440,0.0,0.998,500.0,37
3,Russian,sub1,3,GZ,8,12.440,0.0,0.998,500.0,37
4,Russian,sub1,4,GZ,8,13.440,0.0,0.998,500.0,37
...,...,...,...,...,...,...,...,...,...,...
28254,Spanish,sub9,1262,BACK2,2,3888.518,0.0,0.998,500.0,40
28255,Spanish,sub9,1263,BACK2,2,3890.500,0.0,0.998,500.0,40
28256,Spanish,sub9,1264,BACK2,2,3892.686,0.0,0.998,500.0,40
28257,Spanish,sub9,1265,BACK2,2,3894.826,0.0,0.998,500.0,40
28258,Spanish,sub9,1266,BACK2,2,3897.050,0.0,0.998,500.0,40

In [153]:
import mne
import pandas as pd
from pathlib import Path

mne.set_log_level('WARNING')

BASE = Path(r'D:\Inner Speech Dataset\Inner Speech Dataset')
EXCLUDE = {'GO', 'GZ'}

rows = []
for language in ('Russian', 'Spanish'):
    for fif in sorted((BASE / language).rglob('*-clean-epo.fif')):
        subject = fif.parent.name
        epochs = mne.read_epochs(fif, preload=False, verbose=False)
        id2label = {v: k for k, v in epochs.event_id.items()}

        labels = [id2label.get(code, f'unknown_{code}') for code in epochs.events[:, 2]]
        filtered = [l for l in labels if l not in EXCLUDE]

        per_word = pd.Series(filtered).value_counts()
        rows.append({
            'language':       language,
            'subject':        subject,
            'total_trials':   len(filtered),
            'n_words':        len(per_word),
            'mean_per_word':  round(per_word.mean(), 1) if len(per_word) else 0,
            'min_per_word':   per_word.min() if len(per_word) else 0,
            'max_per_word':   per_word.max() if len(per_word) else 0,
        })

df = pd.DataFrame(rows).set_index(['language', 'subject'])
display(df)

                  total_trials  n_words  mean_per_word  min_per_word  \
language subject
Russian  sub1              684       14           48.9            48
         sub10             672       14           48.0            48
         sub11            1179       14           84.2            81
         sub12             442       14           31.6            26
         sub2             1208       14           86.3            82
         sub3              672       14           48.0            48
         sub4             1219       14           87.1            29
         sub5              684       14           48.9            48
         sub6              358       14           25.6            20
         sub7             1306       14           93.3            85
         sub8             1237       14           88.4            81
         sub9             1286       14           91.9            80
Spanish  sub0             1969       12          164.1            96
         sub1             1571       12          130.9           107
         sub2             2148       12          179.0           148
         sub3             1041       12           86.8            61
         sub4             1108       12           92.3            70
         sub5             1597       12          133.1            73
         sub6             1492       12          124.3           106
         sub7             1560       12          130.0           113
         sub8             1365       12          113.8            90
         sub9             1207       12          100.6            79

                  max_per_word
language subject
Russian  sub1               60
         sub10              48
         sub11              91
         sub12              43
         sub2              104
         sub3               48
         sub4              132
         sub5               60
         sub6               30
         sub7              137
         sub8              108
         sub9              124
Spanish  sub0              255
         sub1              168
         sub2              226
         sub3              106
         sub4              110
         sub5              185
         sub6              160
         sub7              154
         sub8              141
         sub9              127

In [155]:
import mne
import pandas as pd
import numpy as np
from pathlib import Path

mne.set_log_level('WARNING')

BASE = Path(r'D:\Inner Speech Dataset\Inner Speech Dataset')
EXCLUDE = {'GO', 'GZ'}

# Шаг 1: считаем аннотации в EDF по каждому испытуемому
def count_edf_annotations(language):
    rows = []
    for edf in sorted((BASE / language).rglob('*edited.edf')):
        subject = edf.parent.name
        raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
        n_ann = len(raw.annotations)
        rows.append({'language': language, 'subject': subject, 'n_edf_annotations': n_ann})
    return pd.DataFrame(rows)

edf_ru = count_edf_annotations('Russian')
edf_es = count_edf_annotations('Spanish')
edf_counts = pd.concat([edf_ru, edf_es], ignore_index=True)

# Нетипичные: аннотаций < 50% от медианы по языку
for lang, grp in edf_counts.groupby('language'):
    median_n = grp['n_edf_annotations'].median()
    edf_counts.loc[grp.index, 'atypical'] = grp['n_edf_annotations'] < median_n * 0.5

# Шаг 2: считаем эпохи из clean-epo.fif
rows = []
for language in ('Russian', 'Spanish'):
    for fif in sorted((BASE / language).rglob('*-clean-epo.fif')):
        subject = fif.parent.name
        epochs = mne.read_epochs(fif, preload=False, verbose=False)
        id2label = {v: k for k, v in epochs.event_id.items()}

        labels = [id2label.get(code, f'unknown_{code}') for code in epochs.events[:, 2]]
        filtered = [l for l in labels if l not in EXCLUDE]
        per_word = pd.Series(filtered).value_counts()

        rows.append({
            'language':      language,
            'subject':       subject,
            'total_trials':  len(filtered),
            'n_words':       len(per_word),
            'mean_per_word': round(per_word.mean(), 1) if len(per_word) else 0,
            'min_per_word':  int(per_word.min()) if len(per_word) else 0,
            'max_per_word':  int(per_word.max()) if len(per_word) else 0,
            'epoch_len_s':   round(epochs.tmax - epochs.tmin, 3),
        })

df = pd.DataFrame(rows)

# Шаг 3: присоединяем флаг нетипичности
df = df.merge(
    edf_counts[['language', 'subject', 'n_edf_annotations', 'atypical']],
    on=['language', 'subject'], how='left'
)
df['atypical'] = df['atypical'].map({True: '⚠ нетипичный', False: 'норма'})
df = df.set_index(['language', 'subject'])

display(df)

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\3547481275.py:16: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\3547481275.py:16: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\3547481275.py:16: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\3547481275.py:16: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\3547481275.py:16: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)

                  total_trials  n_words  mean_per_word  min_per_word  \
language subject
Russian  sub1              684       14           48.9            48
         sub10             672       14           48.0            48
         sub11            1179       14           84.2            81
         sub12             442       14           31.6            26
         sub2             1208       14           86.3            82
         sub3              672       14           48.0            48
         sub4             1219       14           87.1            29
         sub5              684       14           48.9            48
         sub6              358       14           25.6            20
         sub7             1306       14           93.3            85
         sub8             1237       14           88.4            81
         sub9             1286       14           91.9            80
Spanish  sub0             1969       12          164.1            96
         sub1             1571       12          130.9           107
         sub2             2148       12          179.0           148
         sub3             1041       12           86.8            61
         sub4             1108       12           92.3            70
         sub5             1597       12          133.1            73
         sub6             1492       12          124.3           106
         sub7             1560       12          130.0           113
         sub8             1365       12          113.8            90
         sub9             1207       12          100.6            79

                  max_per_word  epoch_len_s  n_edf_annotations      atypical
language subject
Russian  sub1               60        0.998                 64  ⚠ нетипичный
         sub10              48        0.998                 64  ⚠ нетипичный
         sub11              91        0.998               1366         норма
         sub12              43        0.998                477         норма
         sub2              104        0.998               1395         норма
         sub3               48        0.998                 64  ⚠ нетипичный
         sub4              132        0.998               1372         норма
         sub5               60        0.998                 61  ⚠ нетипичный
         sub6               30        0.998                398  ⚠ нетипичный
         sub7              137        0.998               1343         норма
         sub8              108        0.998               1416         норма
         sub9              124        0.996               1343         норма
Spanish  sub0              255        0.998               1971         норма
         sub1              168        0.998               1573         норма
         sub2              226        0.998               2150         норма
         sub3              106        0.998               1043         норма
         sub4              110        0.998               1110         норма
         sub5              185        0.998               1599         норма
         sub6              160        0.998               1494         норма
         sub7              154        0.998               1562         норма
         sub8              141        0.998               1367         норма
         sub9              127        0.998               1209         норма

In [157]:
import mne
import pandas as pd
import numpy as np
from pathlib import Path

mne.set_log_level('WARNING')

BASE = Path(r'D:\Inner Speech Dataset\Inner Speech Dataset')

WORDS = {
    'BACK1','BACK2','DOWN1','DOWN2','FORWARD1','FORWARD2',
    'LEFT1','LEFT2','NEXT1','NEXT2','RIGHT1','RIGHT2','UP1','UP2'
}

ATYPICAL = {
    ('Russian', 'sub1'), ('Russian', 'sub3'),
    ('Russian', 'sub5'), ('Russian', 'sub6'),
    ('Russian', 'sub10'),
}

rows = []
summary_rows = []

for language in ('Russian', 'Spanish'):
    for edf in sorted((BASE / language).rglob('*_edited.edf')):
        subject = edf.parent.name
        if (language, subject) in ATYPICAL:
            continue

        raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
        ann = raw.annotations
        total_recording_s = raw.times[-1]

        onsets_desc = list(zip(ann.onset, ann.description))

        # Время GO-блока (до первого слова)
        word_onsets = [o for o, d in onsets_desc if d in WORDS]
        if not word_onsets:
            continue
        first_word_t = min(word_onsets)

        go_block_s   = sum(1 for o, d in onsets_desc if d == 'GO' and o < first_word_t)   # кол-во GO-меток до слов
        gz_block_s   = sum(1 for o, d in onsets_desc if d == 'GZ' and o < first_word_t)

        # Группируем словесные метки в блоки
        word_ann = sorted([(o, d) for o, d in onsets_desc if d in WORDS])
        blocks = []
        block_label  = word_ann[0][1]
        block_onsets = [word_ann[0][0]]
        for onset, desc in word_ann[1:]:
            if desc == block_label:
                block_onsets.append(onset)
            else:
                blocks.append({'label': block_label, 'onsets': block_onsets})
                block_label  = desc
                block_onsets = [onset]
        blocks.append({'label': block_label, 'onsets': block_onsets})

        total_word_time_s = 0.0
        total_gap_time_s  = 0.0

        for i, b in enumerate(blocks):
            t_start  = b['onsets'][0]
            t_end    = b['onsets'][-1]
            duration = t_end - t_start
            total_word_time_s += duration

            gap_before = None
            if i > 0:
                gap_before = round(t_start - blocks[i-1]['onsets'][-1], 2)
                total_gap_time_s += gap_before

            rows.append({
                'language':     language,
                'subject':      subject,
                'block_idx':    i,
                'label':        b['label'],
                'n_trials':     len(b['onsets']),
                'block_dur_s':  round(duration, 2),
                'gap_before_s': gap_before,
                'mean_iti_s':   round(np.mean(np.diff(b['onsets'])), 2) if len(b['onsets']) > 1 else None,
            })

        # Время после последнего слова до конца записи
        last_word_t      = blocks[-1]['onsets'][-1]
        tail_s           = round(total_recording_s - last_word_t, 2)

        # Время от старта до первого слова (GO + GZ + прочее)
        preamble_s       = round(first_word_t, 2)

        summary_rows.append({
            'language':           language,
            'subject':            subject,
            'recording_min':      round(total_recording_s / 60, 2),
            'preamble_s':         preamble_s,          # GO+GZ+пауза до первого слова
            'n_word_blocks':      len(blocks),
            'total_word_time_s':  round(total_word_time_s, 1),
            'total_gap_time_s':   round(total_gap_time_s, 1),
            'tail_s':             tail_s,               # после последнего слова
            'mean_block_dur_s':   round(total_word_time_s / len(blocks), 1),
            'mean_gap_s':         round(total_gap_time_s / max(len(blocks)-1, 1), 1),
            'mean_iti_s':         round(np.mean([r['mean_iti_s'] for r in rows
                                                  if r['subject']==subject
                                                  and r['language']==language
                                                  and r['mean_iti_s'] is not None]), 2),
        })

df       = pd.DataFrame(rows)
df_sum   = pd.DataFrame(summary_rows).set_index(['language', 'subject'])

print('=== Структура времени записи (типичные испытуемые) ===')
print("""
Колонки:
  recording_min     — полная длина записи в минутах
  preamble_s        — время до первого слова (GO/GZ блоки + паузы)
  n_word_blocks     — количество словесных блоков
  total_word_time_s — суммарное время внутри блоков (первый→последний трайл блока)
  total_gap_time_s  — суммарное время перерывов МЕЖДУ блоками
  tail_s            — время после последнего трайла до конца записи
  mean_block_dur_s  — средняя длительность одного блока
  mean_gap_s        — средний перерыв между блоками
  mean_iti_s        — средний интервал между трайлами внутри блока
""")
display(df_sum)

print('\n=== Детально по блокам ===')
display(df.set_index(['language', 'subject', 'block_idx']))

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\179055477.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\179055477.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\179055477.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\179055477.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\179055477.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)

=== Структура времени записи (типичные испытуемые) ===

Колонки:
  recording_min     — полная длина записи в минутах
  preamble_s        — время до первого слова (GO/GZ блоки + паузы)
  n_word_blocks     — количество словесных блоков
  total_word_time_s — суммарное время внутри блоков (первый→последний трайл блока)
  total_gap_time_s  — суммарное время перерывов МЕЖДУ блоками
  tail_s            — время после последнего трайла до конца записи
  mean_block_dur_s  — средняя длительность одного блока
  mean_gap_s        — средний перерыв между блоками
  mean_iti_s        — средний интервал между трайлами внутри блока

                  recording_min  preamble_s  n_word_blocks  total_word_time_s  \
language subject
Russian  sub11            92.17      521.10             14             4208.9
         sub12            69.75      188.26             16             3112.1
         sub2             65.68      439.79             14             2775.2
         sub4             65.22      321.47             14             3284.8
         sub7             65.22      318.64             14             3292.6
         sub8             77.98      498.86             14             3064.4
         sub9             66.18      148.08             14             3204.5
Spanish  sub0             88.43      219.91             12             4550.5
         sub1             69.22      162.83             12             3702.0
         sub2             92.37      244.25             12             4616.6
         sub3             64.25      236.53             12             2916.9
         sub4             55.98      357.48             12             2721.5
         sub5             67.62      236.53             12             3427.5
         sub6             79.72      194.29             12             4048.8
         sub7             62.32      193.63             12             3137.7
         sub8             55.05      679.28             12             2185.5
         sub9             65.15      213.63             12             3348.9

                  total_gap_time_s  tail_s  mean_block_dur_s  mean_gap_s  \
language subject
Russian  sub11               787.5   12.56             300.6        60.6
         sub12               742.3  142.29             194.5        49.5
         sub2                715.4   10.62             198.2        55.0
         sub4                298.6    8.05             234.6        23.0
         sub7                293.7    8.05             235.2        22.6
         sub8               1045.5   70.18             218.9        80.4
         sub9                524.1   94.30             228.9        40.3
Spanish  sub0                528.0    7.67             379.2        48.0
         sub1                284.5    3.63             308.5        25.9
         sub2                518.7  162.49             384.7        47.2
         sub3                679.4   22.18             243.1        61.8
         sub4                274.8    5.25             226.8        25.0
         sub5                385.4    7.55             285.6        35.0
         sub6                532.3    7.61             337.4        48.4
         sub7                398.8    8.82             261.5        36.3
         sub8                427.9   10.26             182.1        38.9
         sub9                334.5   11.95             279.1        30.4

                  mean_iti_s
language subject
Russian  sub11          3.62
         sub12          7.12
         sub2           2.33
         sub4           2.90
         sub7           2.53
         sub8           2.52
         sub9           2.52
Spanish  sub0           2.37
         sub1           2.42
         sub2           2.15
         sub3           2.83
         sub4           2.47
         sub5           2.17
         sub6           2.77
         sub7           2.05
         sub8           1.62
         sub9           2.87

=== Детально по блокам ===

                               label  n_trials  block_dur_s  gap_before_s  \
language subject block_idx
Russian  sub11   0               UP1        82       336.52           NaN
                 1               UP2        82       359.74         73.56
                 2             DOWN1        83       303.38         89.19
                 3             DOWN2        86       331.68         73.19
                 4            RIGHT1        82       296.21         68.83
...                              ...       ...          ...           ...
Spanish  sub9    7             LEFT2        90       278.97         11.81
                 8          FORWARD1       100       234.76         16.13
                 9          FORWARD2       103       254.04         13.52
                 10            BACK1       127       277.99         11.25
                 11            BACK2        79       181.30         10.72

                            mean_iti_s
language subject block_idx
Russian  sub11   0                4.15
                 1                4.44
                 2                3.70
                 3                3.90
                 4                3.66
...                                ...
Spanish  sub9    7                3.13
                 8                2.37
                 9                2.49
                 10               2.21
                 11               2.32

[220 rows x 5 columns]

In [158]:
import mne
import pandas as pd
import numpy as np
from pathlib import Path

mne.set_log_level('WARNING')

BASE = Path(r'D:\Inner Speech Dataset\Inner Speech Dataset')

WORDS = {
    'BACK1','BACK2','DOWN1','DOWN2','FORWARD1','FORWARD2',
    'LEFT1','LEFT2','NEXT1','NEXT2','RIGHT1','RIGHT2','UP1','UP2'
}

ATYPICAL = {
    ('Russian', 'sub1'), ('Russian', 'sub3'),
    ('Russian', 'sub5'), ('Russian', 'sub6'),
    ('Russian', 'sub10'),
}

rows = []
summary_rows = []

for language in ('Russian', 'Spanish'):
    for edf in sorted((BASE / language).rglob('*_edited.edf')):
        subject = edf.parent.name
        if (language, subject) in ATYPICAL:
            continue

        raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
        ann = raw.annotations
        total_recording_s = raw.times[-1]

        onsets_desc = list(zip(ann.onset, ann.description))

        word_onsets = [o for o, d in onsets_desc if d in WORDS]
        if not word_onsets:
            continue
        first_word_t = min(word_onsets)

        # Группируем словесные метки в блоки
        word_ann = sorted([(o, d) for o, d in onsets_desc if d in WORDS])
        blocks = []
        block_label  = word_ann[0][1]
        block_onsets = [word_ann[0][0]]
        for onset, desc in word_ann[1:]:
            if desc == block_label:
                block_onsets.append(onset)
            else:
                blocks.append({'label': block_label, 'onsets': block_onsets})
                block_label  = desc
                block_onsets = [onset]
        blocks.append({'label': block_label, 'onsets': block_onsets})

        total_word_time_s = 0.0
        total_gap_time_s  = 0.0

        for i, b in enumerate(blocks):
            t_start  = b['onsets'][0]
            t_end    = b['onsets'][-1]
            duration = t_end - t_start
            total_word_time_s += duration

            gap_before = None
            if i > 0:
                gap_before = round(t_start - blocks[i-1]['onsets'][-1], 2)
                total_gap_time_s += gap_before

            rows.append({
                'language':     language,
                'subject':      subject,
                'block_idx':    i,
                'label':        b['label'],
                'n_trials':     len(b['onsets']),
                'block_dur_min': round(duration / 60, 2),
                'gap_before_min': round(gap_before / 60, 2) if gap_before is not None else None,
                'mean_iti_s':   round(np.mean(np.diff(b['onsets'])), 2) if len(b['onsets']) > 1 else None,
            })

        last_word_t = blocks[-1]['onsets'][-1]

        mean_iti = np.mean([
            r['mean_iti_s'] for r in rows
            if r['subject'] == subject
            and r['language'] == language
            and r['mean_iti_s'] is not None
        ])

        summary_rows.append({
            'language':            language,
            'subject':             subject,
            'recording_min':       round(total_recording_s / 60, 2),
            'preamble_min':        round(first_word_t / 60, 2),
            'n_word_blocks':       len(blocks),
            'total_word_time_min': round(total_word_time_s / 60, 2),
            'total_gap_time_min':  round(total_gap_time_s / 60, 2),
            'tail_min':            round((total_recording_s - last_word_t) / 60, 2),
            'mean_block_dur_min':  round(total_word_time_s / len(blocks) / 60, 2),
            'mean_gap_min':        round(total_gap_time_s / max(len(blocks) - 1, 1) / 60, 2),
            'mean_iti_s':          round(mean_iti, 2),
        })

df     = pd.DataFrame(rows)
df_sum = pd.DataFrame(summary_rows).set_index(['language', 'subject'])

print('=== Структура времени записи (типичные испытуемые) ===')
print("""
Колонки:
  recording_min       — полная длина записи
  preamble_min        — время до первого слова (GO/GZ блоки + паузы)
  n_word_blocks       — количество словесных блоков
  total_word_time_min — суммарное время внутри блоков
  total_gap_time_min  — суммарное время перерывов между блоками
  tail_min            — время после последнего трайла до конца записи
  mean_block_dur_min  — средняя длительность одного блока
  mean_gap_min        — средний перерыв между блоками
  mean_iti_s          — средний интервал между трайлами внутри блока (в секундах)
""")
display(df_sum)

print('\n=== Детально по блокам ===')
display(df.set_index(['language', 'subject', 'block_idx']))

C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1900421995.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1900421995.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1900421995.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1900421995.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
C:\Users\a4431\AppData\Local\Temp\ipykernel_3916\1900421995.py:30: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)

=== Структура времени записи (типичные испытуемые) ===

Колонки:
  recording_min       — полная длина записи
  preamble_min        — время до первого слова (GO/GZ блоки + паузы)
  n_word_blocks       — количество словесных блоков
  total_word_time_min — суммарное время внутри блоков
  total_gap_time_min  — суммарное время перерывов между блоками
  tail_min            — время после последнего трайла до конца записи
  mean_block_dur_min  — средняя длительность одного блока
  mean_gap_min        — средний перерыв между блоками
  mean_iti_s          — средний интервал между трайлами внутри блока (в секундах)

                  recording_min  preamble_min  n_word_blocks  \
language subject
Russian  sub11            92.17          8.68             14
         sub12            69.75          3.14             16
         sub2             65.68          7.33             14
         sub4             65.22          5.36             14
         sub7             65.22          5.31             14
         sub8             77.98          8.31             14
         sub9             66.18          2.47             14
Spanish  sub0             88.43          3.67             12
         sub1             69.22          2.71             12
         sub2             92.37          4.07             12
         sub3             64.25          3.94             12
         sub4             55.98          5.96             12
         sub5             67.62          3.94             12
         sub6             79.72          3.24             12
         sub7             62.32          3.23             12
         sub8             55.05         11.32             12
         sub9             65.15          3.56             12

                  total_word_time_min  total_gap_time_min  tail_min  \
language subject
Russian  sub11                  70.15               13.12      0.21
         sub12                  51.87               12.37      2.37
         sub2                   46.25               11.92      0.18
         sub4                   54.75                4.98      0.13
         sub7                   54.88                4.90      0.13
         sub8                   51.07               17.43      1.17
         sub9                   53.41                8.73      1.57
Spanish  sub0                   75.84                8.80      0.13
         sub1                   61.70                4.74      0.06
         sub2                   76.94                8.64      2.71
         sub3                   48.61               11.32      0.37
         sub4                   45.36                4.58      0.09
         sub5                   57.13                6.42      0.13
         sub6                   67.48                8.87      0.13
         sub7                   52.30                6.65      0.15
         sub8                   36.43                7.13      0.17
         sub9                   55.82                5.57      0.20

                  mean_block_dur_min  mean_gap_min  mean_iti_s
language subject
Russian  sub11                  5.01          1.01        3.62
         sub12                  3.24          0.82        7.12
         sub2                   3.30          0.92        2.33
         sub4                   3.91          0.38        2.90
         sub7                   3.92          0.38        2.53
         sub8                   3.65          1.34        2.52
         sub9                   3.81          0.67        2.52
Spanish  sub0                   6.32          0.80        2.37
         sub1                   5.14          0.43        2.42
         sub2                   6.41          0.79        2.15
         sub3                   4.05          1.03        2.83
         sub4                   3.78          0.42        2.47
         sub5                   4.76          0.58        2.17
         sub6                   5.62          0.81        2.77
         sub7                   4.36          0.60        2.05
         sub8                   3.04          0.65        1.62
         sub9                   4.65          0.51        2.87

=== Детально по блокам ===

                               label  n_trials  block_dur_min  gap_before_min  \
language subject block_idx
Russian  sub11   0               UP1        82           5.61             NaN
                 1               UP2        82           6.00            1.23
                 2             DOWN1        83           5.06            1.49
                 3             DOWN2        86           5.53            1.22
                 4            RIGHT1        82           4.94            1.15
...                              ...       ...            ...             ...
Spanish  sub9    7             LEFT2        90           4.65            0.20
                 8          FORWARD1       100           3.91            0.27
                 9          FORWARD2       103           4.23            0.23
                 10            BACK1       127           4.63            0.19
                 11            BACK2        79           3.02            0.18

                            mean_iti_s
language subject block_idx
Russian  sub11   0                4.15
                 1                4.44
                 2                3.70
                 3                3.90
                 4                3.66
...                                ...
Spanish  sub9    7                3.13
                 8                2.37
                 9                2.49
                 10               2.21
                 11               2.32

[220 rows x 5 columns]

In [159]:
with pd.option_context('display.max_rows', None):
    display(df.set_index(['language', 'subject', 'block_idx']))

                               label  n_trials  block_dur_min  gap_before_min  \
language subject block_idx
Russian  sub11   0               UP1        82           5.61             NaN
                 1               UP2        82           6.00            1.23
                 2             DOWN1        83           5.06            1.49
                 3             DOWN2        86           5.53            1.22
                 4            RIGHT1        82           4.94            1.15
                 5            RIGHT2        91           5.83            1.22
                 6             LEFT1        82           4.63            0.68
                 7             LEFT2        89           5.23            0.69
                 8          FORWARD1        82           5.20            1.08
                 9          FORWARD2        82           4.19            1.10
                 10            BACK1        82           4.93            0.78
                 11            BACK2        89           4.19            1.15
                 12            NEXT1        81           4.63            0.40
                 13            NEXT2        86           4.20            0.95
         sub12   0               UP1        43           6.42             NaN
                 1               UP2        26           2.73            0.95
                 2             DOWN1        34           6.21            0.62
                 3             DOWN2        36           4.94            0.60
                 4            RIGHT1        28           3.25            0.91
                 5            RIGHT2        28           3.07            1.70
                 6             LEFT1        32           3.25            0.85
                 7             LEFT2        31           3.86            1.52
                 8          FORWARD1        30           3.52            0.62
                 9          FORWARD2        31           2.86            0.89
                 10            BACK1        34           3.27            0.74
                 11            BACK2        15           1.58            0.42
                 12            BACK1         1           0.00            0.08
                 13            BACK2        15           1.30            0.76
                 14            NEXT1        28           2.96            1.04
                 15            NEXT2        30           2.65            0.68
         sub2    0               UP1        82           4.38             NaN
                 1               UP2        83           3.59            1.32
                 2             DOWN1        83           3.44            1.77
                 3             DOWN2        84           3.77            0.37
                 4            RIGHT1        91           3.26            2.68
                 5            RIGHT2        86           2.98            0.70
                 6             LEFT1        86           3.20            0.60
                 7             LEFT2        84           2.89            0.95
                 8          FORWARD1        83           3.43            0.63
                 9          FORWARD2        82           2.66            1.20
                 10            BACK1        84           2.99            0.65
                 11            BACK2        87           2.92            0.27
                 12            NEXT1       104           3.48            0.55
                 13            NEXT2        89           3.26            0.23
         sub4    0               UP1       105           6.73             NaN
                 1               UP2        86           3.19            0.27
                 2             DOWN1        86           3.12            0.48
                 3             DOWN2        84           3.51            0.33
                 4            RIGHT1        89           4.08            0.36
                 5            RIGHT2        84           3.13            0.16
                 6             LEFT1        86           3.43            0.32
                 7             LEFT2        85           4.03            0.21
                 8          FORWARD1        87           3.81            0.50
                 9          FORWARD2        91           3.76            0.86
                 10            BACK1        88           3.63            0.42
                 11            BACK2        29           3.20            0.43
                 12            NEXT1       132           6.06            0.44
                 13            NEXT2        87           3.07            0.19
         sub7    0               UP1       108           6.78             NaN
                 1               UP2        91           3.19            0.27
                 2             DOWN1        86           3.12            0.48
                 3             DOWN2        85           3.51            0.33
                 4            RIGHT1        91           4.12            0.31
                 5            RIGHT2        85           3.13            0.16
                 6             LEFT1        87           3.43            0.32
                 7             LEFT2        85           4.03            0.21
                 8          FORWARD1        87           3.81            0.50
                 9          FORWARD2        93           3.76            0.86
                 10            BACK1        88           3.63            0.42
                 11            BACK2        95           3.24            0.39
                 12            NEXT1       137           6.06            0.44
                 13            NEXT2        88           3.07            0.19
         sub8    0               UP1        85           4.31             NaN
                 1               UP2        88           3.18            1.64
                 2             DOWN1        83           3.35            1.71
                 3             DOWN2        95           3.58            0.75
                 4            RIGHT1        83           3.59            0.35
                 5            RIGHT2        86           4.42            0.44
                 6             LEFT1        81           3.47            0.72
                 7             LEFT2       108           4.00            1.76
                 8          FORWARD1        87           4.01            0.58
                 9          FORWARD2        87           3.73            3.04
                 10            BACK1        86           3.58            2.43
                 11            BACK2        86           2.67            2.39
                 12            NEXT1        82           3.73            1.03
                 13            NEXT2       100           3.45            0.57
         sub9    0               UP1        86           3.70             NaN
                 1               UP2        94           3.48            1.60
                 2             DOWN1       124           5.44            0.12
                 3             DOWN2       104           4.31            0.38
                 4            RIGHT1        91           3.67            0.39
                 5            RIGHT2        84           3.17            0.31
                 6             LEFT1        95           4.53            0.33
                 7             LEFT2        84           3.43            0.39
                 8          FORWARD1        88           3.27            2.63
                 9          FORWARD2        94           3.61            0.33
                 10            BACK1        90           3.75            0.50
                 11            BACK2        87           3.69            0.49
                 12            NEXT1        85           3.81            0.84
                 13            NEXT2        80           3.56            0.41
Spanish  sub0    0               UP1        96           5.15             NaN
                 1               UP2       164           9.17            1.20
                 2             DOWN1       119           5.42            0.78
                 3             DOWN2       175           5.95            0.50
                 4            RIGHT1       126           5.11            2.11
                 5            RIGHT2       242          10.44            1.22
                 6             LEFT1       138           4.92            0.61
                 7             LEFT2       186           6.11            0.57
                 8          FORWARD1       159           5.38            0.40
                 9          FORWARD2       255           8.46            0.69
                 10            BACK1       110           3.53            0.42
                 11            BACK2       199           6.20            0.29
         sub1    0               UP1       107           5.86             NaN
                 1               UP2       112           4.93            0.50
                 2             DOWN1       127           4.27            0.36
                 3             DOWN2       126           5.37            0.30
                 4            RIGHT1       133           4.77            0.83
                 5            RIGHT2       131           4.99            0.51
                 6             LEFT1       121           5.55            0.44
                 7             LEFT2       116           5.13            0.17
                 8          FORWARD1       154           4.54            0.33
                 9          FORWARD2       151           6.09            0.41
                 10            BACK1       168           4.92            0.65
                 11            BACK2       125           5.28            0.24
         sub2    0               UP1       214           7.94             NaN
                 1               UP2       158           4.59            0.15
                 2             DOWN1       181          11.26            0.39
                 3             DOWN2       151           5.26            0.29
                 4            RIGHT1       168           8.37            2.27
                 5            RIGHT2       182           5.09            0.57
                 6             LEFT1       148           4.34            0.43
                 7             LEFT2       211           8.59            3.41
                 8          FORWARD1       226           6.71            0.37
                 9          FORWARD2       175           5.19            0.24
                 10            BACK1       165           4.90            0.26
                 11            BACK2       169           4.70            0.25
         sub3    0               UP1        94           5.52             NaN
                 1               UP2        86           4.62            1.02
                 2             DOWN1        89           3.69            0.78
                 3             DOWN2        84           3.88            0.81
                 4            RIGHT1        86           4.05            1.11
                 5            RIGHT2        84           4.05            1.14
                 6             LEFT1       106           5.33            1.47
                 7             LEFT2        61           2.92            0.36
                 8          FORWARD1        88           3.83            1.40
                 9          FORWARD2        86           3.77            0.94
                 10            BACK1        88           3.71            1.13
                 11            BACK2        89           3.25            1.15
         sub4    0               UP1        99           3.02             NaN
                 1               UP2        91           2.73            0.91
                 2             DOWN1        95           3.25            0.17
                 3             DOWN2        75           2.66            0.16
                 4            RIGHT1        89           8.32            0.19
                 5            RIGHT2        70           3.02            0.12
                 6             LEFT1       110           9.14            1.68
                 7             LEFT2        94           2.64            0.48
                 8          FORWARD1        98           2.75            0.43
                 9          FORWARD2        95           2.64            0.16
                 10            BACK1        92           2.47            0.14
                 11            BACK2       100           2.72            0.13
         sub5    0               UP1        73           2.98             NaN
                 1               UP2       140           4.81            1.81
                 2             DOWN1       117           3.94            0.26
                 3             DOWN2       156           5.05            0.29
                 4            RIGHT1       122           5.20            0.46
                 5            RIGHT2       176           7.86            1.15
                 6             LEFT1       143           6.45            0.43
                 7             LEFT2       128           4.34            0.21
                 8          FORWARD1       142           4.79            0.56
                 9          FORWARD2       185           5.23            0.31
                 10            BACK1       102           3.25            0.62
                 11            BACK2       113           3.24            0.32
         sub6    0               UP1       131           4.83             NaN
                 1               UP2       160           5.13            1.86
                 2             DOWN1       115           4.04            0.22
                 3             DOWN2       124           9.51            0.31
                 4            RIGHT1       106           5.09            0.26
                 5            RIGHT2       108           4.23            0.20
                 6             LEFT1       131           4.86            0.15
                 7             LEFT2       115           4.73            0.24
                 8          FORWARD1       132           4.39            0.38
                 9          FORWARD2       136           6.16            0.26
                 10            BACK1       115           9.98            0.34
                 11            BACK2       119           4.54            4.66
         sub7    0               UP1       117           8.14             NaN
                 1               UP2       115           4.51            0.81
                 2             DOWN1       123           3.94            0.20
                 3             DOWN2       144           4.98            0.23
                 4            RIGHT1       139           4.45            0.57
                 5            RIGHT2       119           3.87            0.21
                 6             LEFT1       137           4.09            2.30
                 7             LEFT2       139           4.95            1.37
                 8          FORWARD1       154           3.75            0.41
                 9          FORWARD2       128           3.42            0.21
                 10            BACK1       132           3.25            0.18
                 11            BACK2       113           2.96            0.16
         sub8    0               UP1       101           2.84             NaN
                 1               UP2       109           3.14            0.27
                 2             DOWN1       112           2.69            0.18
                 3             DOWN2       112           2.55            0.15
                 4            RIGHT1       128           3.29            0.16
                 5            RIGHT2       139           3.46            0.19
                 6             LEFT1       104           2.83            0.15
                 7             LEFT2       104           2.94            0.15
                 8          FORWARD1       117           4.46            0.38
                 9          FORWARD2       141           3.44            1.24
                 10            BACK1        90           2.50            4.03
                 11            BACK2       108           2.31            0.22
         sub9    0               UP1       103           4.00             NaN
                 1               UP2       105           3.98            0.49
                 2             DOWN1        80           8.89            0.22
                 3             DOWN2        99           3.98            0.18
                 4            RIGHT1        99           4.13            2.98
                 5            RIGHT2        97           4.11            0.47
                 6             LEFT1       125           6.29            0.19
                 7             LEFT2        90           4.65            0.20
                 8          FORWARD1       100           3.91            0.27
                 9          FORWARD2       103           4.23            0.23
                 10            BACK1       127           4.63            0.19
                 11            BACK2        79           3.02            0.18

                            mean_iti_s
language subject block_idx
Russian  sub11   0                4.15
                 1                4.44
                 2                3.70
                 3                3.90
                 4                3.66
                 5                3.89
                 6                3.43
                 7                3.56
                 8                3.85
                 9                3.10
                 10               3.65
                 11               2.86
                 12               3.47
                 13               2.97
         sub12   0                9.17
                 1                6.55
                 2               11.29
                 3                8.47
                 4                7.22
                 5                6.83
                 6                6.29
                 7                7.72
                 8                7.28
                 9                5.72
                 10               5.94
                 11               6.76
                 12                NaN
                 13               5.55
                 14               6.57
                 15               5.49
         sub2    0                3.25
                 1                2.62
                 2                2.51
                 3                2.72
                 4                2.17
                 5                2.11
                 6                2.26
                 7                2.09
                 8                2.51
                 9                1.97
                 10               2.16
                 11               2.03
                 12               2.03
                 13               2.22
         sub4    0                3.89
                 1                2.25
                 2                2.20
                 3                2.54
                 4                2.78
                 5                2.26
                 6                2.42
                 7                2.88
                 8                2.66
                 9                2.50
                 10               2.50
                 11               6.86
                 12               2.78
                 13               2.14
         sub7    0                3.80
                 1                2.12
                 2                2.20
                 3                2.51
                 4                2.75
                 5                2.23
                 6                2.40
                 7                2.88
                 8                2.66
                 9                2.45

In [161]:
import pandas as pd

data = [
    ('BACK1',      1,  None,   'back',    'назад',     'atrás',      'overt'),
    ('BACK2',      2,     1,   'back',    'назад',     'atrás',      'inner'),
    ('DOWN1',      3,  None,   'down',    'вниз',      'abajo',      'overt'),
    ('DOWN2',      4,     3,   'down',    'вниз',      'abajo',      'inner'),
    ('FORWARD1',   5,  None,   'forward', 'вперёд',    'adelante',   'overt'),
    ('FORWARD2',   6,     5,   'forward', 'вперёд',    'adelante',   'inner'),
    ('GO',         7,     7,   'go',      'старт',     'inicio',     'служебная: начало блока'),
    ('GZ',         8,     8,   'rest',    'покой',     'descanso',   'служебная: отдых/фон'),
    ('LEFT1',      9,  None,   'left',    'влево',     'izquierda',  'overt'),
    ('LEFT2',     10,     9,   'left',    'влево',     'izquierda',  'inner'),
    ('NEXT1',     11,  None,   'next',    'дальше',    '—',          'overt (только RU)'),
    ('NEXT2',     12,  None,   'next',    'дальше',    '—',          'inner (только RU)'),
    ('RIGHT1',    13,  None,   'right',   'вправо',    'derecha',    'overt'),
    ('RIGHT2',    14,    11,   'right',   'вправо',    'derecha',    'inner'),
    ('UP1',       15,  None,   'up',      'вверх',     'arriba',     'overt'),
    ('UP2',       16,    13,   'up',      'вверх',     'arriba',     'inner'),
]

df_labels = pd.DataFrame(data, columns=[
    'label', 'id_russian', 'id_spanish', 'english', 'russian', 'spanish', 'тип'
])

display(df_labels.set_index('label'))

,id_russian,id_spanish,english,russian,spanish,тип
label,,,,,,
BACK1,1,NaN,back,назад,atrás,overt
BACK2,2,1.0,back,назад,atrás,inner
DOWN1,3,NaN,down,вниз,abajo,overt
DOWN2,4,3.0,down,вниз,abajo,inner
FORWARD1,5,NaN,forward,вперёд,adelante,overt
FORWARD2,6,5.0,forward,вперёд,adelante,inner
GO,7,7.0,go,старт,inicio,служебная: начало блока
GZ,8,8.0,rest,покой,descanso,служебная: отдых/фон
LEFT1,9,NaN,left,влево,izquierda,overt
LEFT2,10,9.0,left,влево,izquierda,inner
NEXT1,11,NaN,next,дальше,—,overt (только RU)
NEXT2,12,NaN,next,дальше,—,inner (только RU)
RIGHT1,13,NaN,right,вправо,derecha,overt
RIGHT2,14,11.0,right,вправо,derecha,inner
UP1,15,NaN,up,вверх,arriba,overt
UP2,16,13.0,up,вверх,arriba,inner

In [162]:
import mne
import pandas as pd
from pathlib import Path

mne.set_log_level('WARNING')

BASE = Path(r'D:\Inner Speech Dataset\Inner Speech Dataset')

WORDS = {
    'BACK1','BACK2','DOWN1','DOWN2','FORWARD1','FORWARD2',
    'LEFT1','LEFT2','NEXT1','NEXT2','RIGHT1','RIGHT2','UP1','UP2'
}
SERVICE = {'GO', 'GZ'}

def get_event_ids(language):
    edf = next((BASE / language).rglob('*_edited.edf'))
    raw = mne.io.read_raw_edf(edf, preload=False, verbose=False)
    _, event_id = mne.events_from_annotations(raw, verbose=False)
    return event_id

event_id_ru = get_event_ids('Russian')
event_id_es = get_event_ids('Spanish')

all_labels = sorted(event_id_ru.keys() | event_id_es.keys())

TRANSLATIONS = {
    'BACK':    ('back',    'назад',  'atrás'),
    'DOWN':    ('down',    'вниз',   'abajo'),
    'FORWARD': ('forward', 'вперёд', 'adelante'),
    'LEFT':    ('left',    'влево',  'izquierda'),
    'NEXT':    ('next',    'дальше', '—'),
    'RIGHT':   ('right',   'вправо', 'derecha'),
    'UP':      ('up',      'вверх',  'arriba'),
    'GO':      ('go',      'старт',  'inicio'),
    'GZ':      ('rest',    'покой',  'descanso'),
}

rows = []
for label in all_labels:
    base = label.rstrip('12')
    suffix = label[-1] if label[-1] in ('1', '2') else ''
    en, ru, es = TRANSLATIONS.get(base, (base, base, base))

    if label in SERVICE:
        typ = 'служебная: начало блока' if label == 'GO' else 'служебная: отдых/фон'
    elif suffix == '1':
        typ = 'overt' + (' (только RU)' if label not in event_id_es else '')
    elif suffix == '2':
        typ = 'inner' + (' (только RU)' if label not in event_id_es else '')
    else:
        typ = '—'

    rows.append({
        'label':      label,
        'id_russian': event_id_ru.get(label),
        'id_spanish': event_id_es.get(label),
        'english':    en,
        'russian':    ru,
        'spanish':    es,
        'тип':        typ,
    })

df_labels = pd.DataFrame(rows).set_index('label')
display(df_labels)

,id_russian,id_spanish,english,russian,spanish,тип
label,,,,,,
BACK1,1,1.0,back,назад,atrás,overt
BACK2,2,2.0,back,назад,atrás,inner
DOWN1,3,3.0,down,вниз,abajo,overt
DOWN2,4,4.0,down,вниз,abajo,inner
FORWARD1,5,5.0,forward,вперёд,adelante,overt
FORWARD2,6,6.0,forward,вперёд,adelante,inner
GO,7,7.0,go,старт,inicio,служебная: начало блока
GZ,8,8.0,rest,покой,descanso,служебная: отдых/фон
LEFT1,9,9.0,left,влево,izquierda,overt
LEFT2,10,10.0,left,влево,izquierda,inner
NEXT1,11,NaN,next,дальше,—,overt (только RU)
NEXT2,12,NaN,next,дальше,—,inner (только RU)
RIGHT1,13,11.0,right,вправо,derecha,overt
RIGHT2,14,12.0,right,вправо,derecha,inner
UP1,15,13.0,up,вверх,arriba,overt
UP2,16,14.0,up,вверх,arriba,inner